// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_waltona1.Models;

namespace Mission6_waltona1.Migrations
{
    [DbContext(typeof(MovieFormContext))]
    [Migration("20230218204946_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6_waltona1.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Adventure"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Fantasy"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Horror"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Musical"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Mystery"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Science Fiction"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Sports"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Thriller"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Western"
                        });
                });

            modelBuilder.Entity("Mission6_waltona1.Models.FormResponse", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("FormId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            FormId = 1,
                            CategoryId = 4,
                            director = "Not Sure",
                            edited = false,
                            lent = "no",
                            notes = "N/A",
                            rating = "PG-13",
                            title = "Glass Onion",
                            year = 2022
                        },
                        new
                        {
                            FormId = 2,
                            CategoryId = 1,
                            director = "Not Sure",
                            edited = false,
                            lent = "yes",
                            notes = "N/A",
                            rating = "PG-13",
                            title = "Red Notice",
                            year = 2022
                        },
                        new
                        {
                            FormId = 3,
                            CategoryId = 9,
                            director = "Not Sure",
                            edited = false,
                            lent = "yes",
                            notes = "N/A",
                            rating = "PG-13",
                            title = "Me Before You",
                            year = 2016
                        });
                });

            modelBuilder.Entity("Mission6_waltona1.Models.FormResponse", b =>
                {
                    b.HasOne("Mission6_waltona1.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
