// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_waltona1.Models;

namespace Mission6_waltona1.Migrations
{
    [DbContext(typeof(MovieFormContext))]
    [Migration("20230213205534_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6_waltona1.Models.FormResponse", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("FormId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            FormId = 1,
                            category = "Comedy",
                            director = "Not Sure",
                            edited = false,
                            lent = "no",
                            notes = "N/A",
                            rating = "PG-13",
                            title = "Glass Onion",
                            year = 2022
                        },
                        new
                        {
                            FormId = 2,
                            category = "Adventure",
                            director = "Not Sure",
                            edited = false,
                            lent = "yes",
                            notes = "N/A",
                            rating = "PG-13",
                            title = "Red Notice",
                            year = 2022
                        },
                        new
                        {
                            FormId = 3,
                            category = "Drama",
                            director = "Not Sure",
                            edited = false,
                            lent = "yes",
                            notes = "N/A",
                            rating = "PG-13",
                            title = "Me Before You",
                            year = 2016
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
